package com.airpool.Model;

/**
 * Created by Maury on 10/17/14.
 */
public enum Airport {
    BHM("Birmingham","Alabama","AL","Birmingham_Shuttlesworth International Airport","BHM"),
    DHN("Dothan","Alabama","AL","Dothan Regional Airport","DHN"),
    HSV("Huntsville","Alabama","AL","Huntsville International Airport","HSV"),
    MOB("Mobile","Alabama","AL","Mobile Regional Airport","MOB"),
    MGM("Montgomery","Alabama","AL","Montgomery Regional Airport","MGM"),
    ANC("Anchorage","Alaska","AK","Ted Stevens Anchorage International Airport","ANC"),
    ANI("Aniak","Alaska","AK","Aniak Airport","ANI"),
    BRW("Barrow","Alaska","AK","Wiley Post_Will Rogers Memorial Airport","BRW"),
    BET("Bethel","Alaska","AK","Bethel Airport","BET"),
    CDV("Cordova","Alaska","AK","Merle K. Smith Airport","CDV"),
    SCC("Deadhorse / Prudhoe Bay","Alaska","AK","Deadhorse Airport","SCC"),
    DLG("Dillingham","Alaska","AK","Dillingham Airport","DLG"),
    FAI("Fairbanks","Alaska","AK","Fairbanks International Airport","FAI"),
    GAL("Galena","Alaska","AK","Edward G. Pitka Sr. Airport","GAL"),
    GST("Gustavus","Alaska","AK","Gustavus Airport","GST"),
    HNS("Haines","Alaska","AK","Haines Airport","HNS"),
    HOM("Homer","Alaska","AK","Homer Airport","HOM"),
    HNH("Hoonah","Alaska","AK","Hoonah Airport","HNH"),
    JNU("Juneau","Alaska","AK","Juneau International Airport","JNU"),
    ENA("Kenai","Alaska","AK","Kenai Municipal Airport","ENA"),
    KTN("Ketchikan","Alaska","AK","Ketchikan International Airport","KTN"),
    AKN("King Salmon","Alaska","AK","King Salmon Airport","AKN"),
    ADQ("Kodiak","Alaska","AK","Kodiak Airport","ADQ"),
    OTZ("Kotzebue","Alaska","AK","Ralph Wien Memorial Airport","OTZ"),
    OME("Nome","Alaska","AK","Nome Airport","OME"),
    PSG("Petersburg","Alaska","AK","Petersburg James A. Johnson Airport","PSG"),
    SIT("Sitka","Alaska","AK","Sitka Rocky Gutierrez Airport","SIT"),
    KSM("St. Mary's","Alaska","AK","St. Mary's Airport","KSM"),
    UNK("Unalakleet","Alaska","AK","Unalakleet Airport","UNK"),
    DUT("Unalaska","Alaska","AK","Unalaska Airport","DUT"),
    VDZ("Valdez","Alaska","AK","Valdez Airport","VDZ"),
    WRG("Wrangell","Alaska","AK","Wrangell Airport","WRG"),
    YAK("Yakutat","Alaska","AK","Yakutat Airport","YAK"),
    IFP("Bullhead City","Arizona","AZ","Laughlin/Bullhead International Airport","IFP"),
    FLG("Flagstaff","Arizona","AZ","Flagstaff Pulliam Airport","FLG"),
    GCN("Grand Canyon / Tusayan","Arizona","AZ","Grand Canyon National Park Airport","GCN"),
    IWA("Mesa","Arizona","AZ","Phoenix_Mesa Gateway Airport","IWA"),
    PGA("Page","Arizona","AZ","Page Municipal Airport","PGA"),
    PGS("Peach Springs","Arizona","AZ","Grand Canyon West Airport","PGS"),
    PHX("Phoenix","Arizona","AZ","Phoenix Sky Harbor International Airport","PHX"),
    TUS("Tucson","Arizona","AZ","Tucson International Airport","TUS"),
    NYL("Yuma","Arizona","AZ","Yuma International Airport","NYL"),
    XNA("Fayetteville","Arkansas","AR","Northwest Arkansas Regional Airport","XNA"),
    FSM("Fort Smith","Arkansas","AR","Fort Smith Regional Airport","FSM"),
    LIT("Little Rock","Arkansas","AR","Bill and Hillary Clinton National Airport","LIT"),
    TXK("Texarkana","Arkansas","AR","Texarkana Regional Airport","TXK"),
    ACV("Arcata / Eureka","California","CA","Arcata Airport","ACV"),
    BFL("Bakersfield","California","CA","Meadows Field","BFL"),
    BUR("Burbank","California","CA","Bob Hope Airport","BUR"),
    CRQ("Carlsbad","California","CA","McClellan_Palomar Airport","CRQ"),
    CIC("Chico","California","CA","Chico Municipal Airport","CIC"),
    CEC("Crescent City","California","CA","Del Norte County Airport","CEC"),
    FAT("Fresno","California","CA","Fresno Yosemite International Airport","FAT"),
    LGB("Long Beach","California","CA","Long Beach Airport","LGB"),
    LAX("Los Angeles","California","CA","Los Angeles International Airport","LAX"),
    MMH("Mammoth Lakes","California","CA","Mammoth Yosemite Airport","MMH"),
    MOD("Modesto","California","CA","Modesto City_County Airport","MOD"),
    MRY("Monterey","California","CA","Monterey Regional Airport","MRY"),
    OAK("Oakland","California","CA","Oakland International Airport","OAK"),
    ONT("Ontario","California","CA","Ontario International Airport","ONT"),
    PSP("Palm Springs","California","CA","Palm Springs International Airport","PSP"),
    RDD("Redding","California","CA","Redding Municipal Airport","RDD"),
    SMF("Sacramento","California","CA","Sacramento International Airport","SMF"),
    SAN("San Diego","California","CA","San Diego International Airport","SAN"),
    SFO("San Francisco","California","CA","San Francisco International Airport","SFO"),
    SJC("San Jose","California","CA","Norman Y. Mineta San Jos_ International Airport","SJC"),
    SBP("San Luis Obispo","California","CA","San Luis Obispo County Regional Airport","SBP"),
    SNA("Santa Ana","California","CA","John Wayne Airport _ Orange County","SNA"),
    SBA("Santa Barbara","California","CA","Santa Barbara Municipal Airport","SBA"),
    SMX("Santa Maria","California","CA","Santa Maria Public Airport","SMX"),
    STS("Santa Rosa","California","CA","Charles M. Schulz_Sonoma County Airport","STS"),
    SCK("Stockton","California","CA","Stockton Metropolitan Airport","SCK"),
    ASE("Aspen","Colorado","CO","Aspen-Pitkin County Airport","ASE"),
    COS("Colorado Springs","Colorado","CO","City of Colorado Springs Municipal Airport","COS"),
    DEN("Denver","Colorado","CO","Denver International Airport","DEN"),
    DRO("Durango","Colorado","CO","Durango-La Plata County Airport","DRO"),
    EGE("Eagle","Colorado","CO","Eagle County Regional Airport","EGE"),
    GJT("Grand Junction","Colorado","CO","Grand Junction Regional Airport","GJT"),
    GUC("Gunnison","Colorado","CO","Gunnison-Crested Butte Regional Airport","GUC"),
    HDN("Hayden","Colorado","CO","Yampa Valley Airport","HDN"),
    MTJ("Montrose","Colorado","CO","Montrose Regional Airport","MTJ"),
    BDL("Hartford","Connecticut","CT","Bradley International Airport","BDL"),
    HVN("New Haven","Connecticut","CT","Tweed New Haven Regional Airport","HVN"),
    DAB("Daytona Beach","Florida","FA","Daytona Beach International Airport","DAB"),
    FLL("Fort Lauderdale","Florida","FA","Fort Lauderdale_Hollywood International Airport","FLL"),
    RSW("Fort Myers","Florida","FA","Southwest Florida International Airport","RSW"),
    GNV("Gainesville","Florida","FA","Gainesville Regional Airport","GNV"),
    JAX("Jacksonville","Florida","FA","Jacksonville International Airport","JAX"),
    EYW("Key West","Florida","FA","Key West International Airport","EYW"),
    MLB("Melbourne","Florida","FA","Melbourne International Airport","MLB"),
    MIA("Miami","Florida","FA","Miami International Airport","MIA"),
    MCO("Orlando","Florida","FA","Orlando International Airport","MCO"),
    SFB("Orlando","Florida","FA","Orlando Sanford International Airport","SFB"),
    ECP("Panama City Beach","Florida","FA","Northwest Florida Beaches International Airport","ECP"),
    PNS("Pensacola","Florida","FA","Pensacola International Airport","PNS"),
    PGD("Punta Gorda","Florida","FA","Punta Gorda Airport","PGD"),
    SRQ("Sarasota / Bradenton","Florida","FA","Sarasota_Bradenton International Airport","SRQ"),
    PIE("St. Petersburg","Florida","FA","St. Petersburg_Clearwater International Airport","PIE"),
    TLH("Tallahassee","Florida","FA","Tallahassee Regional Airport","TLH"),
    TPA("Tampa","Florida","FA","Tampa International Airport","TPA"),
    VPS("Valparaiso","Florida","FA","Northwest Florida Regional Airport","VPS"),
    PBI("West Palm Beach","Florida","FA","Palm Beach International Airport","PBI"),
    ABY("Albany","Georgia","GA","Southwest Georgia Regional Airport","ABY"),
    ATL("Atlanta","Georgia","GA","Hartsfield-Jackson Atlanta International Airport","ATL"),
    AGS("Augusta","Georgia","GA","Augusta Regional Airport","AGS"),
    BQK("Brunswick","Georgia","GA","Brunswick Golden Isles Airport","BQK"),
    CSG("Columbus","Georgia","GA","Columbus Metropolitan Airport","CSG"),
    SAV("Savannah","Georgia","GA","Savannah/Hilton Head International Airport","SAV"),
    VLD("Valdosta","Georgia","GA","Valdosta Regional Airport","VLD"),
    ITO("Hilo","Hawaii","HI","Hilo International Airport","ITO"),
    HNL("Honolulu","Hawaii","HI","Honolulu International Airport","HNL"),
    OGG("Kahului","Hawaii","HI","Kahului Airport","OGG"),
    KOA("Kailua/Kona","Hawaii","HI","Kona International Airport at Keahole","KOA"),
    MKK("Kaunakakai","Hawaii","HI","Molokai Airport","MKK"),
    LNY("Lanai City (Lanai City)","Hawaii","HI","Lanai Airport","LNY"),
    LIH("Lihue (Lihue)","Hawaii","HI","Lihue Airport","LIH"),
    BOI("Boise","Idaho","ID","Boise Airport","BOI"),
    SUN("Hailey","Idaho","ID","Friedman Memorial Airport","SUN"),
    IDA("Idaho Falls","Idaho","ID","Idaho Falls Regional Airport","IDA"),
    LWS("Lewiston","Idaho","ID","Lewiston-Nez Perce County Airport","LWS"),
    PIH("Pocatello / Arbon Valley","Idaho","ID","Pocatello Regional Airport","PIH"),
    TWF("Twin Falls","Idaho","ID","Magic Valley Regional Airport","TWF"),
    BLV("Belleville","Illinois","IL","MidAmerica St. Louis Airport","BLV"),
    BMI("Bloomington / Normal","Illinois","IL","Central Illinois Regional Airport at Bloomington-Normal","BMI"),
    CMI("Champaign / Urbana","Illinois","IL","University of Illinois - Willard Airport","CMI"),
    ORD("Chicago","Illinois","IL","Chicago O'Hare International Airport","ORD"),
    MDW("Chicago","Illinois","IL","Chicago Midway International Airport","MDW"),
    MWA("Marion","Illinois","IL","Williamson County Regional Airport","MWA"),
    MLI("Moline","Illinois","IL","Quad City International Airport","MLI"),
    PIA("Peoria","Illinois","IL","General Downing - Peoria International Airport","PIA"),
    UIN("Quincy","Illinois","IL","Quincy Regional Airport","UIN"),
    RFD("Rockford","Illinois","IL","Chicago Rockford International Airport","RFD"),
    SPI("Springfield","Illinois","IL","Abraham Lincoln Capital Airport","SPI"),
    EVV("Evansville","Indiana","IN","Evansville Regional Airport","EVV"),
    FWA("Fort Wayne","Indiana","IN","Fort Wayne International Airport","FWA"),
    IND("Indianapolis","Indiana","IN","Indianapolis International Airport","IND"),
    SBN("South Bend","Indiana","IN","South Bend International Airport","SBN"),
    CID("Cedar Rapids","Iowa","IA","The Eastern Iowa Airport","CID"),
    DSM("Des Moines","Iowa","IA","Des Moines International Airport","DSM"),
    DBQ("Dubuque","Iowa","IA","Dubuque Regional Airport","DBQ"),
    SUX("Sioux City","Iowa","IA","Sioux Gateway Airport","SUX"),
    ALO("Waterloo","Iowa","IA","Waterloo Regional Airport","ALO"),
    GCK("Garden City","Kansas","KS","Garden City Regional Airport","GCK"),
    MHK("Manhattan","Kansas","KS","Manhattan Regional Airport","MHK"),
    ICT("Wichita","Kansas","KS","Wichita Dwight D. Eisenhower National Airport","ICT"),
    CVG("Covington","Kentucky","KY","Cincinnati/Northern Kentucky International Airport","CVG"),
    LEX("Lexington","Kentucky","KY","Blue Grass Airport","LEX"),
    SDF("Louisville","Kentucky","KY","Louisville International Airport","SDF"),
    OWB("Owensboro","Kentucky","KY","Owensboro-Daviess County Regional Airport","OWB"),
    PAH("Paducah","Kentucky","KY","Barkley Regional Airport","PAH"),
    AEX("Alexandria","Louisiana","LA","Alexandria International Airport","AEX"),
    BTR("Baton Rouge","Louisiana","LA","Baton Rouge Metropolitan Airport","BTR"),
    LFT("Lafayette","Louisiana","LA","Lafayette Regional Airport","LFT"),
    LCH("Lake Charles","Louisiana","LA","Lake Charles Regional Airport","LCH"),
    MLU("Monroe","Louisiana","LA","Monroe Regional Airport","MLU"),
    MSY("New Orleans","Louisiana","LA","Louis Armstrong New Orleans International Airport","MSY"),
    SHV("Shreveport","Louisiana","LA","Shreveport Regional Airport","SHV"),
    BGR("Bangor","Maine","ME","Bangor International Airport","BGR"),
    BHB("Bar Harbor","Maine","ME","Hancock County-Bar Harbor Airport","BHB"),
    PWM("Portland","Maine","ME","Portland International Jetport","PWM"),
    PQI("Presque Isle","Maine","ME","Northern Maine Regional Airport at Presque Isle","PQI"),
    RKD("Rockland","Maine","ME","Knox County Regional Airport","RKD"),
    BWI("Baltimore / Glen Burnie","Maryland","MD","Baltimore/Washington International Thurgood Marshall Airport","BWI"),
    SBY("Salisbury","Maryland","MD","Salisbury-Ocean City Wicomico Regional Airport","SBY"),
    HGR("Hagerstown","Maryland","MD","Hagerstown Regional Airport","HGR"),
    BOS("Boston","Massachusetts","MA","Gen. Edward Lawrence Logan International Airport","BOS"),
    HYA("Hyannis","Massachusetts","MA","Barnstable Municipal Airport","HYA"),
    ACK("Nantucket","Massachusetts","MA","Nantucket Memorial Airport","ACK"),
    EWB("New Bedford","Massachusetts","MA","New Bedford Regional Airport","EWB"),
    PVC("Provincetown","Massachusetts","MA","Provincetown Municipal Airport","PVC"),
    MVY("Vineyard Haven","Massachusetts","MA","Martha's Vineyard Airport","MVY"),
    APN("Alpena","Michigan","MI","Alpena County Regional Airport","APN"),
    CVX("Charlevoix","Michigan","MI","Charlevoix Municipal Airport","CVX"),
    DTW("Detroit / Romulus","Michigan","MI","Detroit Metropolitan Wayne County Airport","DTW"),
    ESC("Escanaba","Michigan","MI","Delta County Airport","ESC"),
    FNT("Flint","Michigan","MI","Bishop International Airport","FNT"),
    GRR("Grand Rapids","Michigan","MI","Gerald R. Ford International Airport","GRR"),
    CMX("Hancock / Calumet","Michigan","MI","Houghton County Memorial Airport","CMX"),
    IMT("Iron Mountain / Kingsford","Michigan","MI","Ford Airport","IMT"),
    AZO("Kalamazoo / Battle Creek","Michigan","MI","Kalamazoo/Battle Creek International Airport","AZO"),
    LAN("Lansing","Michigan","MI","Capital Region International Airport","LAN"),
    SAW("Marquette / Gwinn","Michigan","MI","Sawyer International Airport","SAW"),
    MKG("Muskegon","Michigan","MI","Muskegon County Airport","MKG"),
    PLN("Pellston","Michigan","MI","Pellston Regional Airport of Emmet County","PLN"),
    MBS("Saginaw","Michigan","MI","MBS International Airport","MBS"),
    CIU("Sault Ste. Marie","Michigan","MI","Chippewa County International Airport","CIU"),
    TVC("Traverse City","Michigan","MI","Cherry Capital Airport","TVC"),
    BJI("Bemidji","Minnesota","MN","Bemidji Regional Airport","BJI"),
    BRD("Brainerd","Minnesota","MN","Brainerd Lakes Regional Airport","BRD"),
    DLH("Duluth","Minnesota","MN","Duluth International Airport","DLH"),
    HIB("Hibbing","Minnesota","MN","Range Regional Airport","HIB"),
    INL("International Falls","Minnesota","MN","Falls International Airport","INL"),
    MSP("Minneapolis","Minnesota","MN","Minneapolis_St. Paul International Airport","MSP"),
    RST("Rochester","Minnesota","MN","Rochester International Airport","RST"),
    STC("St. Cloud","Minnesota","MN","St. Cloud Regional Airport","STC"),
    GTR("Columbus / West Point / Starkville","Mississippi","MS","Golden Triangle Regional Airport","GTR"),
    GPT("Gulfport / Biloxi","Mississippi","MS","Gulfport-Biloxi International Airport","GPT"),
    PIB("Hattiesburg / Laurel","Mississippi","MS","Hattiesburg-Laurel Regional Airport","PIB"),
    JAN("Jackson","Mississippi","MS","Jackson-Evers International Airport","JAN"),
    COU("Columbia","Missouri","MO","Columbia Regional Airport","COU"),
    JLN("Joplin","Missouri","MO","Joplin Regional Airport","JLN"),
    MCI("Kansas City","Missouri","MO","Kansas City International Airport","MCI"),
    SGF("Springfield","Missouri","MO","Springfield-Branson National Airport","SGF"),
    STL("St. Louis","Missouri","MO","Lambert-St. Louis International Airport","STL"),
    BIL("Billings","Montana","MT","Billings Logan International Airport","BIL"),
    BZN("Bozeman","Montana","MT","Bozeman Yellowstone International Airport","BZN"),
    BTM("Butte","Montana","MT","Bert Mooney Airport","BTM"),
    GTF("Great Falls","Montana","MT","Great Falls International Airport","GTF"),
    HLN("Helena","Montana","MT","Helena Regional Airport","HLN"),
    GPI("Kalispell","Montana","MT","Glacier Park International Airport","GPI"),
    MSO("Missoula","Montana","MT","Missoula International Airport","MSO"),
    GRI("Grand Island","Nebraska","NE","Central Nebraska Regional Airport","GRI"),
    EAR("Kearney","Nebraska","NE","Kearney Regional Airport","EAR"),
    LNK("Lincoln","Nebraska","NE","Lincoln Airport","LNK"),
    OMA("Omaha","Nebraska","NE","Eppley Airfield","OMA"),
    BFF("Scottsbluff","Nebraska","NE","Western Nebraska Regional Airport","BFF"),
    BVU("Boulder City","Nevada","NV","Boulder City Municipal Airport","BVU"),
    EKO("Elko","Nevada","NV","Elko Regional Airport","EKO"),
    LAS("Las Vegas","Nevada","NV","McCarran International Airport","LAS"),
    RNO("Reno","Nevada","NV","Reno/Tahoe International Airport","RNO"),
    LEB("Lebanon","New Hampshire","NH","Lebanon Municipal Airport","LEB"),
    MHT("Manchester","New Hampshire","NH","Manchester-Boston Regional Airport","MHT"),
    ACY("Atlantic City","New Jersey","NJ","Atlantic City International Airport","ACY"),
    TTN("Trenton","New Jersey","NJ","Trenton Mercer Airport","TTN"),
    EWR("Newark","New Jersey","NJ","Newark Liberty International Airport","EWR"),
    ABQ("Albuquerque","New Mexico","NM","Albuquerque International Sunport","ABQ"),
    FMN("Farmington","New Mexico","NM","Four Corners Regional Airport","FMN"),
    HOB("Hobbs","New Mexico","NM","Lea County Regional Airport","HOB"),
    ROW("Roswell","New Mexico","NM","Roswell International Air Center","ROW"),
    SAF("Santa Fe","New Mexico","NM","Santa Fe Municipal Airport","SAF"),
    ALB("Albany","New York","NY","Albany International Airport","ALB"),
    BGM("Binghamton","New York","NY","Greater Binghamton Airport","BGM"),
    BUF("Buffalo","New York","NY","Buffalo Niagara International Airport","BUF"),
    ELM("Elmira / Corning","New York","NY","Elmira/Corning Regional Airport","ELM"),
    ISP("Islip","New York","NY","Long Island MacArthur Airport","ISP"),
    ITH("Ithaca","New York","NY","Ithaca Tompkins Regional Airport","ITH"),
    JFK("New York","New York","NY","John F. Kennedy International Airport","JFK"),
    LGA("New York","New York","NY","LaGuardia Airport","LGA"),
    SWF("Newburgh","New York","NY","Stewart International Airport","SWF"),
    IAG("Niagara Falls","New York","NY","Niagara Falls International Airport","IAG"),
    PBG("Plattsburgh","New York","NY","Plattsburgh International Airport","PBG"),
    ROC("Rochester","New York","NY","Greater Rochester International Airport","ROC"),
    SYR("Syracuse","New York","NY","Syracuse Hancock International Airport","SYR"),
    ART("Watertown","New York","NY","Watertown International Airport","ART"),
    HPN("White Plains","New York","NY","Westchester County Airport","HPN"),
    AVL("Asheville","North Carolina","NC","Asheville Regional Airport","AVL"),
    CLT("Charlotte","North Carolina","NC","Charlotte/Douglas International Airport","CLT"),
    FAY("Fayetteville","North Carolina","NC","Fayetteville Regional Airport","FAY"),
    GSO("Greensboro","North Carolina","NC","Piedmont Triad International Airport","GSO"),
    PGV("Greenville","North Carolina","NC","Pitt-Greenville Airport","PGV"),
    OAJ("Jacksonville","North Carolina","NC","Albert J. Ellis Airport","OAJ"),
    EWN("New Bern","North Carolina","NC","Coastal Carolina Regional Airport","EWN"),
    RDU("Raleigh","North Carolina","NC","Raleigh-Durham International Airport","RDU"),
    ILM("Wilmington","North Carolina","NC","Wilmington International Airport","ILM"),
    BIS("Bismarck","North Dakota","ND","Bismarck Municipal Airport","BIS"),
    DIK("Dickinson","North Dakota","ND","Dickinson Theodore Roosevelt Regional Airport","DIK"),
    FAR("Fargo","North Dakota","ND","Hector International Airport","FAR"),
    GFK("Grand Forks","North Dakota","ND","Grand Forks International Airport","GFK"),
    MOT("Minot","North Dakota","ND","Minot International Airport","MOT"),
    ISN("Williston","North Dakota","ND","Sloulin Field International Airport","ISN"),
    CAK("Akron / Canton","Ohio","OH","Akron-Canton Regional Airport","CAK"),
    CLE("Cleveland","Ohio","OH","Cleveland-Hopkins International Airport","CLE"),
    CMH("Columbus","Ohio","OH","Port Columbus International Airport","CMH"),
    LCK("Columbus","Ohio","OH","Rickenbacker International Airport","LCK"),
    DAY("Dayton","Ohio","OH","James M. Cox Dayton International Airport","DAY"),
    TOL("Toledo","Ohio","OH","Toledo Express Airport","TOL"),
    YNG("Youngstown / Warren","Ohio","OH","Youngstown-Warren Regional Airport","YNG"),
    LAW("Lawton","Oklahoma","OK","Lawton_Fort Sill Regional Airport","LAW"),
    OKC("Oklahoma City","Oklahoma","OK","Will Rogers World Airport","OKC"),
    TUL("Tulsa","Oklahoma","OK","Tulsa International Airport","TUL"),
    EUG("Eugene","Oregon","OR","Eugene Airport","EUG"),
    LMT("Klamath Falls","Oregon","OR","Klamath Falls Airport","LMT"),
    MFR("Medford","Oregon","OR","Rogue Valley International-Medford Airport","MFR"),
    OTH("North Bend","Oregon","OR","Southwest Oregon Regional Airport","OTH"),
    PDX("Portland","Oregon","OR","Portland International Airport","PDX"),
    RDM("Redmond","Oregon","OR","Redmond Municipal Airport","RDM"),
    ABE("Allentown","Pennsylvania","PA","Lehigh Valley International Airport","ABE"),
    ERI("Erie","Pennsylvania","PA","Erie International Airport","ERI"),
    MDT("Harrisburg / Middletown","Pennsylvania","PA","Harrisburg International Airport","MDT"),
    LBE("Latrobe","Pennsylvania","PA","Arnold Palmer Regional Airport","LBE"),
    PHL("Philadelphia","Pennsylvania","PA","Philadelphia International Airport","PHL"),
    PIT("Pittsburgh","Pennsylvania","PA","Pittsburgh International Airport","PIT"),
    UNV("State College","Pennsylvania","PA","University Park Airport","UNV"),
    AVP("Wilkes-Barre / Scranton","Pennsylvania","PA","Wilkes-Barre/Scranton International Airport","AVP"),
    IPT("Williamsport","Pennsylvania","PA","Williamsport Regional Airport","IPT"),
    PVD("Providence / Warwick","Rhode Island","RI","Theodore Francis Green State Airport","PVD"),
    WST("Westerly","Rhode Island","RI","Westerly State Airport","WST"),
    CHS("Charleston","South Carolina","SC","Charleston International Airport","CHS"),
    CAE("Columbia","South Carolina","SC","Columbia Metropolitan Airport","CAE"),
    FLO("Florence","South Carolina","SC","Florence Regional Airport","FLO"),
    GSP("Greer","South Carolina","SC","Greenville-Spartanburg International Airport","GSP"),
    HXD("Hilton Head Island","South Carolina","SC","Hilton Head Airport","HXD"),
    MYR("Myrtle Beach","South Carolina","SC","Myrtle Beach International Airport","MYR"),
    ABR("Aberdeen","South Dakota","SD","Aberdeen Regional Airport","ABR"),
    PIR("Pierre","South Dakota","SD","Pierre Regional Airport","PIR"),
    RAP("Rapid City","South Dakota","SD","Rapid City Regional Airport","RAP"),
    FSD("Sioux Falls","South Dakota","SD","Sioux Falls Regional Airport","FSD"),
    TRI("Bristol / Johnson City / Kingsport","Tennessee","TN","Tri-Cities Regional Airport","TRI"),
    CHA("Chattanooga","Tennessee","TN","Chattanooga Metropolitan Airport","CHA"),
    TYS("Knoxville","Tennessee","TN","McGhee Tyson Airport","TYS"),
    MEM("Memphis","Tennessee","TN","Memphis International Airport","MEM"),
    BNA("Nashville","Tennessee","TN","Nashville International Airport","BNA"),
    ABI("Abilene","Texas","TX","Abilene Regional Airport","ABI"),
    AMA("Amarillo","Texas","TX","Rick Husband Amarillo International Airport","AMA"),
    AUS("Austin","Texas","TX","Austin-Bergstrom International Airport","AUS"),
    BPT("Beaumont / Port Arthur","Texas","TX","Jack Brooks Regional Airport","BPT"),
    BRO("Brownsville","Texas","TX","Brownsville/South Padre Island International Airport","BRO"),
    CLL("College Station","Texas","TX","Easterwood Airport","CLL"),
    CRP("Corpus Christie/ Kingsville","Texas","TX","Corpus Christi International Airport","CRP"),
    DAL("Dallas","Texas","TX","Dallas Love Field","DAL"),
    DFW("Dallas-Fort Worth","Texas","TX","Dallas/Fort Worth International Airport","DFW"),
    DRT("Del Rio","Texas","TX","Del Rio International Airport","DRT"),
    ELP("El Paso","Texas","TX","El Paso International Airport","ELP"),
    GRK("Fort Hood / killeen / Temple","Texas","TX","Killeen-Fort Hood Regional Airport?/ Robert Gray Army Airfield","GRK"),
    HRL("Harlingen","Texas","TX","Valley International Airport","HRL"),
    IAH("Houston","Texas","TX","George Bush Intercontinental Airport","IAH"),
    HOU("Houston","Texas","TX","William P. Hobby Airport","HOU"),
    LRD("Laredo","Texas","TX","Laredo International Airport","LRD"),
    GGG("Longview","Texas","TX","East Texas Regional Airport","GGG"),
    LBB("Lubbock","Texas","TX","Lubbock Preston Smith International Airport","LBB"),
    MFE("McAllen","Texas","TX","McAllen-Miller International Airport","MFE"),
    MAF("Midland","Texas","TX","Midland International Airport","MAF"),
    SJT("San Angelo","Texas","TX","San Angelo Regional Airport","SJT"),
    SAT("San Antonio","Texas","TX","San Antonio International Airport","SAT"),
    TYR("Tyler","Texas","TX","Tyler Pounds Regional Airport","TYR"),
    ACT("Waco","Texas","TX","Waco Regional Airport","ACT"),
    SPS("Wichita Falls","Texas","TX","Wichita Falls Municipal Airport","SPS"),
    PVU("Provo","Utah","UT","Provo Municipal Airport","PVU"),
    SLC("Salt Lake City","Utah","UT","Salt Lake City International Airport","SLC"),
    SGU("St. George / Beaver","Utah","UT","St. George Municipal Airport","SGU"),
    ENV("Wendover","Utah","UT","Wendover Airport","ENV"),
    BTV("Burlington","Vermont","VT","Burlington International Airport","BTV"),
    CHO("Charlottesville","Virginia","VA","Charlottesville_Albemarle Airport","CHO"),
    LYH("Lynchburg","Virginia","VA","Lynchburg Regional Airport","LYH"),
    PHF("Newport News","Virginia","VA","Newport News/Williamsburg International Airport","PHF"),
    ORF("Norfolk","Virginia","VA","Norfolk International Airport","ORF"),
    RIC("Richmond","Virginia","VA","Richmond International Airport","RIC"),
    ROA("Roanoke","Virginia","VA","Roanoke Regional Airport","ROA"),
    SHD("Staunton / Waynesboro / Harrisonburg","Virginia","VA","Shenandoah Valley Regional Airport","SHD"),
    DCA("Washington, D.C. / Arlington County","Virginia","VA","Ronald Reagan Washington National Airport","DCA"),
    IAD("Washington, D.C. / Chantilly / Dulles","Virginia","VA","Washington Dulles International Airport","IAD"),
    BLI("Bellingham","Washington","WA","Bellingham International Airport","BLI"),
    FHR("Friday Harbor","Washington","WA","Friday Harbor Airport","FHR"),
    PSC("Pasco","Washington","WA","Tri-Cities Airport","PSC"),
    CLM("Port Angeles","Washington","WA","William R. Fairchild International Airport","CLM"),
    PUW("Pullman / Moscow, Idaho","Washington","WA","Pullman/Moscow Regional Airport","PUW"),
    BFI("Seattle","Washington","WA","King County International Airport","BFI"),
    SEA("Seattle / Tacoma (SeaTac)","Washington","WA","Seattle_Tacoma International Airport","SEA"),
    GEG("Spokane","Washington","WA","Spokane International Airport","GEG"),
    ALW("Walla Walla","Washington","WA","Walla Walla Regional Airport","ALW"),
    EAT("Wenatchee","Washington","WA","Pangborn Memorial Airport","EAT"),
    YKM("Yakima","Washington","WA","Yakima Air Terminal","YKM"),
    CRW("Charleston","West Virginia","WV","Yeager Airport","CRW"),
    CKB("Clarksburg","West Virginia","WV","North Central West Virginia Airport","CKB"),
    HTS("Huntington","West Virginia","WV","Tri-State Airport","HTS"),
    LWB("Lewisburg","West Virginia","WV","Greenbrier Valley Airport","LWB"),
    MGW("Morgantown","West Virginia","WV","Morgantown Municipal Airport","MGW"),
    ATW("Appleton","Wisconsin","WI","Outagamie County Regional Airport","ATW"),
    EAU("Eau Claire","Wisconsin","WI","Chippewa Valley Regional Airport","EAU"),
    GRB("Green Bay","Wisconsin","WI","Austin Straubel International Airport","GRB"),
    LSE("La Crosse","Wisconsin","WI","La Crosse Regional Airport","LSE"),
    MSN("Madison","Wisconsin","WI","Dane County Regional Airport","MSN"),
    MKE("Milwaukee","Wisconsin","WI","General Mitchell International Airport","MKE"),
    CWA("Wausau","Wisconsin","WI","Central Wisconsin Airport","CWA"),
    RHI("Rhinelander","Wisconsin","WI","Rhinelander-Oneida County Airport","RHI"),
    CPR("Casper","Wyoming","WY","Casper/Natrona County International Airport","CPR"),
    CYS("Cheyenne","Wyoming","WY","Cheyenne Regional Airport","CYS"),
    COD("Cody","Wyoming","WY","Yellowstone Regional Airport","COD"),
    GCC("Gillette","Wyoming","WY","Gillette-Campbell County Airport","GCC"),
    JAC("Jackson","Wyoming","WY","Jackson Hole Airport","JAC"),
    LAR("Laramie","Wyoming","WY","Laramie Regional Airport","LAR"),
    RIW("Riverton","Wyoming","WY","Riverton Regional Airport","RIW"),
    RKS("Rock Springs","Wyoming","WY","Rock Springs Sweetwater County Airport","RKS"),
    SHR("Sheridan","Wyoming","WY","Sheridan County Airport","SHR"),
    PPG("Pago Pago, Tutuila","American Samoa","AS","Pago Pago International Airport","PPG"),
    GUM("Agana / Tamuning","Guam","GU","Antonio B. Won Pat International Airport","GUM"),
    GSN("Obyan, Saipan Island","Northern Marianas","MP","Saipan International Airport","GSN"),
    GRO("Rota Island","Northern Marianas","MP","Rota International Airport","GRO"),
    BQN("Aguadilla","Puerto Rico","PR","Rafael Hernandez International Airport","BQN"),
    PSE("Ponce","Puerto Rico","PR","Mercedita International Airport","PSE"),
    SJU("San Juan / Carolina","Puerto Rico","PR","Luis Munoz Marin International Airport","SJU"),
    SIG("San Juan / Miramar","Puerto Rico","PR","Fernando Luis Ribas Dominicci Airport","SIG"),
    VQS("Vieques","Puerto Rico","PR","Antonio Rivera Rodriguez Airport","VQS"),
    STT("Charlotte Amalie, St. Thomas","U.S. Virgin Islands","VI","Cyril E. King Airport","STT"),
    STX("Christiansted, St. Croix","U.S. Virgin Islands","VI","Henry E. Rohlsen Airport","STX");

    private String city;
    private String state;
    private String stateAbbreviation;
    private String airportName;
    private String airportAbbreviation;

    private Airport(String city, String state, String stateAbbreviation,
                    String airportName, String airportAbbreviation) {
        this.city = city;
        this.state = state;
        this.stateAbbreviation = stateAbbreviation;
        this.airportName = airportName;
        this.airportAbbreviation = airportAbbreviation;
    }

    public String getCity() {
        return this.city;
    }

    public String getState() {
        return this.state;
    }

    public String getStateAbbreviation() {
        return this.stateAbbreviation;
    }

    public String getAirportName() {
        return this.airportName;
    }

    public String getAirportAbbreviation() {
        return this.airportAbbreviation;
    }

};